# Generated by Django 6.1.1 on 2026-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("price", models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
