# Generated by Django 6.1.1 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="external_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
