# Generated by Django 6.1.1 on 2026-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_station_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="positive_fuel_price"
            ),
        ),
    ]
