# Generated by Django 6.1.1 on 2026-10-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_station_price_and_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=250)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("state", "key"), name="unique_place_key"
                    )
                ],
            },
        ),
    ]
